#!/usr/bin/env bash
# Script to display DNS resolution for subdomains
resolve_subdomain() {
    sub="$1"
    domain="$2"
    result=$(dig +short $sub.$domain)
    record=$(dig $sub.$domain | awk '/^;; ANSWER SECTION:$/ { getline; print $4 }')
    echo "Subdomain $sub is a $record record with IP $result"
}

subdomains=("www" "lb-01" "web-01" "web-02")

if [ $# -eq 1 ]; then
    domain="$1"
    for sub in "${subdomains[@]}"; do
        resolve_subdomain "$sub" "$domain"
    done
elif [ $# -eq 2 ]; then
    domain="$1"
    sub="$2"
    resolve_subdomain "$sub" "$domain"
fi
