#!/usr/bin/env bash
# Setting up and verifying DNS records

# Function to show details of a subdomain
show_details() {
    local domain="$1"
    local sub="$2"
    local ip_addr=$(dig +short $sub.$domain)
    local record=$(dig $sub.$domain | awk '/^;; ANSWER SECTION:$/ { getline; print $4 }')

    echo "The subdomain $sub is a $record record and points to $ip_addr"
}

# Main script logic
domain="$1"
sub="$2"

if [ -z "$sub" ]; then
    show_details "$domain" www
    show_details "$domain" lb-01
    show_details "$domain" web-01
    show_details "$domain" web-02
else
    show_details "$domain" "$sub"
fi
