#!/usr/bin/env bash
# Script to transfer a file from client to server using scp

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
    exit 1
fi

FILE="$1"
IP="$2"
USERNAME="$3"
SSH_KEY="$4"
DESTINATION="~/"

if [ -z "$SSH_KEY" ]; then
    scp -o StrictHostKeyChecking=no "$FILE" "$USERNAME@$IP":"$DESTINATION"
else
    scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME@$IP":"$DESTINATION"
fi
