#!/usr/bin/env bash
# Resolving Nginx not listening on port 80

sudo rm -f /etc/nginx/sites-enabled/default
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo systemctl restart nginx
