#!/usr/bin/env bash
# Configures a server to listen on port 80 of all server's active IPv4 IPs
sudo sed -i "s/listen 8080/listen 80/" /etc/nginx/sites-available/default
sudo systemctl restart nginx
sudo truncate -s 0 /run/nginx.pid
