#!/usr/bin/env bash
# Fixing Nginx not listening on port 80

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
sudo systemctl kill --signal=TERM nginx
