#!/usr/bin/env bash
# Manages 'manage_my_process'

case "${1}" in
    start)
        ./manage_my_process &
        echo "$!" | sudo tee /var/run/my_process.pid >/dev/null
        echo "manage_my_process started"
        ;;
    stop)
        echo "manage_my_process stopped"
        sudo kill "$(cat /var/run/my_process.pid)"
        sudo rm -f /var/run/my_process.pid
        ;;
    restart)
        echo "manage_my_process restarted"
        sudo kill "$(cat /var/run/my_process.pid)"
        sudo rm -f /var/run/my_process.pid
        ./manage_my_process &
        echo "$!" | sudo tee /var/run/my_process.pid >/dev/null
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
