#!/usr/bin/env bash
# Parses an Apache log file and displays the IP and HTTP code for each visitor, along with the number of occurrences.

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr
