#!/usr/bin/env bash
# Displays "Best School" 10 times, except on the 9th iteration it displays "Hi".

counter=0
while [ "$counter" -lt 10 ]; do
    if [ "$counter" -eq 8 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
