#!/usr/bin/env bash
# Displays "Best School" 10 times, with custom messages on the 4th and 8th iteration.

counter=1
while [ "$counter" -lt 11 ]; do
    if [ "$counter" -eq 4 ]; then
        echo "bad luck"
    elif [ "$counter" -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
